# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a67ddd97c82ff6a5a463bce50679ae1dc1ac1c5221e26485104c76304c7f25d8b70d22ca6bda13255a2eae3a9090759d95bfa200d74dceda72d2cb27a046b01f

test:
  secret_key_base: 4e5f895f47a7ba5f622a57aac7bc3dd101bf60b184cffb1eac01b0fd2fd2c91b970075e8c844f3b9de7460dbad470e511406af312897062b787f4020a522c785

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
